"use client";

import { useState } from "react";
import Link from "next/link";
import { DashboardShell } from "../../components/dashboard-shell";
import { Icon } from "../../components/printx-ui";

const queueJobs = [
  { token: "A7K2", document: "project-brief.pdf", pages: "12 pages · Color", printer: "Printer 02", customer: "Alex Rivera", status: "Printing", className: "printing", time: "2 min" },
  { token: "C4P6", document: "menu-summer.pdf", pages: "4 pages · Color", printer: "Printer 01", customer: "Walk-in request", status: "Queued", className: "queued", time: "Waiting" },
  { token: "F1D9", document: "invoice-2048.pdf", pages: "2 pages · B&W", printer: "Printer 03", customer: "Jordan Lee", status: "Queued", className: "queued", time: "Waiting" },
  { token: "K8W3", document: "poster-final.jpg", pages: "1 page · Color", printer: "Printer 02", customer: "Maya Chen", status: "Completed", className: "completed", time: "9:56 AM" },
];

const printers = [
  { name: "Printer 01", model: "HP LaserJet Pro", status: "Online", jobs: "12 jobs today", level: "82%", tone: "green" },
  { name: "Printer 02", model: "Canon imageRUNNER", status: "Printing", jobs: "23 jobs today", level: "68%", tone: "blue" },
  { name: "Printer 03", model: "Epson WorkForce", status: "Online", jobs: "13 jobs today", level: "44%", tone: "purple" },
];

export default function BusinessDashboard() {
  const [queuePaused, setQueuePaused] = useState(false);

  return (
    <DashboardShell workspace="business">
      <div className="dashboard-heading"><div><span className="dashboard-eyebrow">BUSINESS WORKSPACE · N7K4Q2</span><h1>Good morning, Northstar.</h1><p>Here is what is happening across your print network.</p></div><div className="dashboard-heading-actions"><button className="outline-action" onClick={() => setQueuePaused((current) => !current)}><span className={`queue-toggle-dot ${queuePaused ? "paused" : ""}`} /> {queuePaused ? "Resume queue" : "Queue is live"}</button><Link href="#printers" className="button dashboard-action"><Icon name="plus" size={17} /> Add printer</Link></div></div>

      <section className="metric-grid business-metrics"><div className="metric-card"><span className="metric-icon green"><Icon name="clock" size={18} /></span><span><small>JOBS TODAY</small><strong>48</strong></span><em className="metric-positive">↑ 14% from yesterday</em></div><div className="metric-card"><span className="metric-icon gold"><Icon name="wallet" size={18} /></span><span><small>TODAY&apos;S REVENUE</small><strong>$286<span>.40</span></strong></span><em className="metric-positive">↑ 8.2% this week</em></div><div className="metric-card"><span className="metric-icon blue"><Icon name="clock" size={18} /></span><span><small>AVERAGE WAIT</small><strong>06<span> min</span></strong></span><em>Within your 10 min target</em></div><div className="metric-card"><span className="metric-icon purple"><Icon name="printer" size={18} /></span><span><small>PRINTER UPTIME</small><strong>98<span>.7%</span></strong></span><em>3 of 3 devices online</em></div></section>

      <div className="business-dashboard-grid"><section className="dashboard-card queue-dashboard-card" id="queue"><div className="card-heading"><div><span className="card-kicker">LIVE OPERATIONS</span><h2>Print queue</h2></div><div className="queue-heading-actions"><span className={`live-badge ${queuePaused ? "paused" : ""}`}><i /> {queuePaused ? "Paused" : "Live now"}</span><button className="card-link">Manage queue <Icon name="arrow" size={14} /></button></div></div><div className="queue-table-head"><span>JOB</span><span>DOCUMENT</span><span>PRINTER</span><span>STATUS</span><span>TIME</span></div><div className="business-queue-list">{queueJobs.map((job) => <div className="business-queue-row" key={job.token}><span className="business-job-token">{job.token}</span><span className="business-document"><Icon name="file" size={17} /><span><strong>{job.document}</strong><small>{job.customer} · {job.pages}</small></span></span><span className="assigned-printer"><Icon name="printer" size={14} /> {job.printer}</span><span className={`queue-status ${job.className}`}><i /> {job.status}</span><span className="queue-time">{job.time}</span></div>)}</div><div className="queue-footer-action"><button className="card-link">Open full queue <Icon name="arrow" size={14} /></button><span><Icon name="check" size={14} /> Jobs are routed automatically</span></div></section><section className="dashboard-card fleet-card" id="printers"><div className="card-heading"><div><span className="card-kicker">DEVICE HEALTH</span><h2>Printer fleet</h2></div><button className="card-link">View all <Icon name="arrow" size={14} /></button></div><div className="fleet-list">{printers.map((printer) => <div className="fleet-row" key={printer.name}><span className={`fleet-printer-icon ${printer.tone}`}><Icon name="printer" size={18} /></span><span className="fleet-copy"><strong>{printer.name}</strong><small>{printer.model}</small></span><span className={`fleet-status ${printer.status === "Printing" ? "working" : ""}`}><i /> {printer.status}</span><span className="fleet-meta"><strong>{printer.level}</strong><small>{printer.jobs}</small></span></div>)}</div><button className="fleet-manage"><Icon name="settings" size={15} /> Configure printers</button></section></div>

      <div className="business-bottom-grid"><section className="dashboard-card earnings-card" id="pricing"><div className="card-heading"><div><span className="card-kicker">PERFORMANCE</span><h2>Revenue overview</h2></div><button className="period-select">Last 7 days <Icon name="chevron" size={14} /></button></div><div className="revenue-value"><strong>$1,842<span>.60</span></strong><span className="metric-positive">↑ 12.4%</span></div><div className="chart"><div className="chart-y"><span>$400</span><span>$200</span><span>$0</span></div><div className="chart-area"><div className="chart-gridline one" /><div className="chart-gridline two" /><div className="chart-gridline three" /><svg viewBox="0 0 600 150" preserveAspectRatio="none" aria-label="Revenue trend"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#8dc7a6" stopOpacity=".3" /><stop offset="1" stopColor="#8dc7a6" stopOpacity="0" /></linearGradient></defs><path d="M0 119 C50 107 62 112 95 92 S144 96 175 82 S225 95 263 68 S310 76 345 80 S393 50 425 57 S475 48 510 29 S553 51 600 16 V150 H0Z" fill="url(#chartFill)" /><path d="M0 119 C50 107 62 112 95 92 S144 96 175 82 S225 95 263 68 S310 76 345 80 S393 50 425 57 S475 48 510 29 S553 51 600 16" fill="none" stroke="#4d9972" strokeWidth="3" /></svg><div className="chart-x"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></div></section><section className="dashboard-card team-card" id="team"><div className="card-heading"><div><span className="card-kicker">TEAM ACCESS</span><h2>Team members</h2></div><button className="card-link"><Icon name="plus" size={14} /> Invite</button></div><div className="team-list"><div className="team-row"><span className="team-avatar green-avatar">AR</span><span><strong>Alex Rivera</strong><small>Administrator</small></span><span className="team-active"><i /> Active</span></div><div className="team-row"><span className="team-avatar gold-avatar">JM</span><span><strong>Jordan Miller</strong><small>Operator</small></span><span className="team-active"><i /> Active</span></div><div className="team-row"><span className="team-avatar purple-avatar">SK</span><span><strong>Sam Kim</strong><small>Operator</small></span><span className="team-invited">Invite pending</span></div></div><button className="team-manage">Manage team access <Icon name="arrow" size={14} /></button></section></div>
    </DashboardShell>
  );
}
